# ==============================
# XOUND - Configuración
# ==============================

# Servidor
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:8080/xound_db
spring.datasource.username=postgres
spring.datasource.password=LeviPeralta09
spring.datasource.driver-class-name=org.postgresql.Driver

# Inicializar schema SQL al arrancar
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# JWT
jwt.secret=xound-secret-key-cambiar-en-produccion-debe-ser-larga-256bits
jwt.expiration=86400000
